version: '3'

services:
  postgres:
        image: postgres:10.5
        restart: always
        container_name: reviews-db
        env_file: .env
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=
          - POSTGRES_DB=$DBNAME
        logging:
          options:
            max-size: 10m
            max-file: "3"
        ports:
          - '5438:5432'
        volumes:
          - pgdata:/var/lib/postgresql/data
          # # copy the sql script to create tables
          # - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
volumes:
  pgdata:
    external: false